import Foundation
import WebKit

// ─────────────────────────────────────────────────────────────────────────────
// POTokenManager
//
// YouTube requires a Proof-of-Origin (PO) token generated by running their
// BotGuard JavaScript challenge. We do this by loading YouTube in a hidden
// WKWebView and extracting the token via JavaScript injection.
// This is the same approach used by browser-based yt-dlp plugins.
// ─────────────────────────────────────────────────────────────────────────────

@MainActor
class POTokenManager: NSObject, ObservableObject {
    static let shared = POTokenManager()

    private var webView: WKWebView?
    private var pendingContinuation: CheckedContinuation<String, Error>?
    private var tokenCache: [String: (token: String, expires: Date)] = [:]

    override init() {
        super.init()
        setupWebView()
    }

    private func setupWebView() {
        let config = WKWebViewConfiguration()
        config.websiteDataStore = WKWebsiteDataStore.default()
        let wv = WKWebView(frame: .zero, configuration: config)
        wv.navigationDelegate = self
        // Share cookies with AuthManager's webview
        self.webView = wv
    }

    // ── Get PO token for a video ID ───────────────────────────────────────
    func getToken(for videoId: String, visitorData: String) async throws -> String {
        // Check cache first (tokens are bound per videoId)
        if let cached = tokenCache[videoId],
           cached.expires > Date() {
            return cached.token
        }

        // Load YouTube watch page in hidden webview to trigger BotGuard
        guard let wv = webView else { throw POError("WebView not available") }

        return try await withCheckedThrowingContinuation { continuation in
            self.pendingContinuation = continuation

            let url = URL(string: "https://www.youtube.com/watch?v=\(videoId)")!
            wv.load(URLRequest(url: url))
        }
    }

    // ── Extract PO token from loaded page ─────────────────────────────────
    private func extractPOToken(videoId: String) {
        guard let wv = webView else { return }

        // Inject JS to extract the PO token from YouTube's player config
        let js = """
        (function() {
            try {
                // Try to get from ytcfg
                if (window.ytcfg && ytcfg.data_) {
                    var data = ytcfg.data_;
                    if (data.VISITOR_DATA) {
                        return JSON.stringify({
                            visitorData: data.VISITOR_DATA,
                            poToken: data.INNERTUBE_CONTEXT_CLIENT_INFO ?
                                     data.INNERTUBE_CONTEXT_CLIENT_INFO.po_token || '' : ''
                        });
                    }
                }
                // Try from yt.config_
                if (window.yt && yt.config_) {
                    var cfg = yt.config_;
                    return JSON.stringify({
                        visitorData: cfg.VISITOR_DATA || '',
                        poToken: cfg.INNERTUBE_CONTEXT_CLIENT_INFO ?
                                 cfg.INNERTUBE_CONTEXT_CLIENT_INFO.po_token || '' : ''
                    });
                }
                return JSON.stringify({visitorData: '', poToken: ''});
            } catch(e) {
                return JSON.stringify({error: e.message});
            }
        })();
        """

        wv.evaluateJavaScript(js) { [weak self] result, error in
            guard let self = self else { return }
            guard let jsonStr = result as? String,
                  let data = jsonStr.data(using: .utf8),
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: String]
            else {
                self.pendingContinuation?.resume(throwing: POError("JS extraction failed"))
                self.pendingContinuation = nil
                return
            }

            let token = json["poToken"] ?? ""
            let visitorData = json["visitorData"] ?? ""

            if !token.isEmpty {
                // Cache for 1 hour
                self.tokenCache[videoId] = (token, Date().addingTimeInterval(3600))
                self.pendingContinuation?.resume(returning: token)
            } else if !visitorData.isEmpty {
                // No PO token but got visitor data — use empty token
                // Some clients work with just visitor data + cookies
                self.pendingContinuation?.resume(returning: "")
            } else {
                self.pendingContinuation?.resume(returning: "")
            }
            self.pendingContinuation = nil
        }
    }
}

extension POTokenManager: WKNavigationDelegate {
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        guard let url = webView.url?.absoluteString,
              url.contains("youtube.com/watch") else { return }
        // Wait briefly for YouTube's JS to initialize
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            if let videoId = url.components(separatedBy: "v=").last?
                                .components(separatedBy: "&").first {
                self.extractPOToken(videoId: videoId)
            }
        }
    }

    func webView(_ webView: WKWebView, didFail navigation: WKNavigation!,
                 withError error: Error) {
        pendingContinuation?.resume(throwing: error)
        pendingContinuation = nil
    }
}

struct POError: LocalizedError {
    let msg: String
    init(_ msg: String) { self.msg = msg }
    var errorDescription: String? { msg }
}
